# Interactive component
This is a interactive webpage related to our project. You can choose to guess the states rank top five on number of library or museum in the state and click the bar to get the answer. By clicking on the button, you can choose to switch from library to museum or vice versa. Hope you enjoy this!
<script src="https://d3js.org/d3.v7.js"></script>

<h1>Check state ranks of owing libraries or museums </h1>

<button type="button" id="library" class="btn btn-default" value="library">Library</button>
<button type="button" id="museum" class="btn btn-default" value="museum">Museum</button>

<div id="plot"></div>
<script>

// Create svg and initial bars

  const w = 800;
  const h = 600;
  const margin = {top: 50, right: 0, bottom: 50,
      left: 50};
  const innerWidth = w - margin.left - margin.right;
  const innerHeight = h - margin.top - margin.bottom;

  const bardata = [{num:"1226",stat:"California"},{num:"1083",stat:"New York"},{num:"893",stat:"Texas"},{num:"792",stat:"Illinois"},{num:"777",stat:"Ohio"}];
  
  const mubardata = [{num:"2409",stat:"California"},{num:"2020",stat:"New York"},{num:"1682",stat:"Texas"},{num:"1495",stat:"Pennsylvania"},{num:"1243",stat:"Ohio"}];
  
  const bardata2=[1226,1083,893,792,777];
  const mubardata2=[2409,2020,1682,1495,1243];
  
  drawbars(bardata,bardata2);
  
  function drawbars(dataset,dataset2){ 
    var name='libraries'
    if (dataset==mubardata){
         name='museums'
    };
    const xScale = d3.scaleBand()
        .domain(d3.range(dataset.length))
        .range([0, innerWidth])
        .paddingInner(.1);
  
    const yScale = d3.scaleLinear()
        .domain([0, d3.max(dataset2)])
        .range([innerHeight, 0])
  
    const xAxis = d3.axisBottom()
        .scale(xScale);
  
    const yAxis = d3.axisLeft()
        .scale(yScale);
  
  // add svg
  
    const svg = d3.select("div#plot")
      .append("svg")
        .attr("width", w)
        .attr("height", h);
  
  // add background rectangle
  
    svg.append("rect")
        .attr("x", 0)
        .attr("y", 0)
        .attr("width", w)
        .attr("height", h)
        .attr("fill", "aliceblue");
  
// add bars as a group

    const bars = svg.append("g")
        .attr("id", "plot")
        .attr("transform", `translate (${margin.left}, ${margin.top})`)
        .selectAll("rect")
        .data(dataset);
  
    bars.enter().append("rect")
        .attr("id",d=>d.stat)
        .attr("x", (d, i) => xScale(i))
        .attr("y", d => yScale(d.num))
        .attr("width", xScale.bandwidth())
        .attr("height", d => innerHeight - yScale(d.num))
        .attr("fill", "lightgreen");
        
  //add labels
    d3.select("g")
        .selectAll("text")
        .data(dataset2)
        .enter()
        .append("text")
        .attr("x", (d, i) => xScale(i) + .5*xScale.bandwidth())
        .attr("y", d => yScale(d) + 25)
        .text(d=>d)
        .attr("fill", "blue")
        .attr("text-anchor", "middle");
  
  // add axes
    svg.append("g")
        .attr("class", "xAxis")
        .attr("transform", `translate (${margin.left}, ${h - margin.bottom})`)
        .call(xAxis);
  
    svg.append("g")
        .attr("class", "yAxis")
        .attr("transform", `translate (${margin.left}, ${margin.top})`)
        .call(yAxis);
        
  //interaction text
    d3.select("g")
        .append("text")
        .attr("x", d => w/2)
        .attr("y", d => 0)
        .text(`Guess who ranks top on having ${name}?`)
        .attr("fill", "black")
        .attr("font-size","20")
        .attr("text-anchor", "middle");
      d3.select("g")
        .append("text")
        .attr("x", d => w/2)
        .attr("y", d => 20)
        .text('(click the bar to find out the answer)')
        .attr("fill", "black")
        .attr("font-size","20")
        .attr("text-anchor", "middle");
  
    //interaction
    d3.selectAll("rect")
      .on("click", function(event) {
      const state = d3.select(event.currentTarget).attr("id");
      const dx=d3.select(event.currentTarget).attr("x");
      const dy=d3.select(event.currentTarget).attr("y");
      if (state != null){
        d3.select("g")
          .append("text")
          //d3.select("text")
          .attr("x",d=>dx)
          .attr("y",d=>dy)
          .text(`This is ${state} state.`);
        d3.select(event.currentTarget).attr("fill","pink");
        }
        });
}
    d3.select("#library")
        .on("click", function () {
         d3.selectAll("svg").remove()
         drawbars(bardata,bardata2)
        });  
        
     d3.select("#museum")
     .on("click", function () {
        d3.select("svg").remove()
        drawbars(mubardata,mubardata2)
    });
 </script>
