# Proposal

## Research topic

Our research topic is about the museums and public libraries across the US. 

For the museums, there are different kinds of museums including art museums, history museums and so on. We are interested in the number of different kinds of museum countrywide and statewide. Also, different states have different number of museums which partly reflect the culture and development of individual states. Some of the museum are free to visit while some need to buy ticket, thus we would like to further analyze the income of individual museums.

For the libraries, some libraries provide readers more than printed materials, such as audio and e-books and analyzing the number of books and other resources of a library can reflect the scale of the library. As many of libraries were built especially for the local resident and we would like to analyze relationship between the number of people visit the library or register in the library and the population of that area. Some of the libraries have librarian and we are also interested in their salary and also other aspect related to the economic condition of the library including their revenue. Also, to analyze the influence of modern technology, we would like to analyze the trend of the number of visitors of libraries.

Moreover, as both the construction of museum and library are part of the culture development of a region, we will put data of library and museum together and explore whether their are some similarity between public library and museum in the same region which can reflect how much importance local government put on the culture development.

In a word, our research focus on the number of museums and libraries across the nation as well as their scale and operation condition. By analyzing the distribution of the museums and libraries in different region, we try to analyze the local culture development.

## Data availability

The data used in this project are from the official website of the Institute of Museum and Library Services(IMLS):
https://www.imls.gov/research-tools/data-collection . It contains information about location, discipline, revenues, etc. All datasets are in .csv format, which simplifies the data import process. 

The museum data are consisted of three datasets, and can be downloaded by link: https://www.imls.gov/sites/default/files/2018_csv_museum_data_files.zip .
According to the Data File Documentation and User’s Guide for museum data on the website, the first release of these files is from 2013 to 2015 (FY 2014 Q1, FY 2015 Q1 and FY 2015 Q3, where "FY" stands for "Fiscal Year", and "Q" stands for "Quarter"). The final cleaning and construction are from 2017-2018, which gives the newest (current) data version. Researchers of IMLS collected the data from multiple sources, for example, IMLS administrative records and lists of grantees from private foundations. The duplicate data during the collecting process were removed by combining statistical algorithms and manual entry review, guaranteeing data reliability.

Each of the three files has the same data structure: one row per museum or related organization, with 50 column variables. During data import process, we will select the variables which are related to our research topic. For example, we can explore the distribution of museum over different locations by comparing `AAMREG`, `BEAREG`, `LOCALE4` (geographical variables) with `Museum Discipline`. Then, we can obtain information about the number of museums in each state and the distribution of museum types among different states. We can also explore the relationship between museum income and types by comparing `INCOMECD15` and `Museum Discipline`.

The library data has been collected annually since 1988, but the electronic records are from 1992 to 2020. We will first use the most recent three datasets released in 2020: https://www.imls.gov/sites/default/files/2022-07/pls_fy2020_csv.zip . The data are collected using public libraries survey by recording the time, location, citizen satisfaction with library service, etc. To be more specific, surveys are distributed by data coordinators in each state, and then collected back from local public libraries. During the data import process, we will select the variables which demonstrate the number of visitors, amount of books, and revenue, of local libraries and then analyze the relationship between them. We will also analyze the development of libraries over time by using the relevant data from different years.

To compare the similarity or differences between public libraries and museums in the same region, we will use these two datasets: https://www.imls.gov/sites/default/files/pnlms_pudf_csv.zip, which demonstrate the public needs for libraries and museums. The data were collected through a random-digit dialing telephone survey, which includes visitation to libraries and museums, attitudes toward library and museum services, and demographics. Hence, these two datasets provide sufficient information to analyze our research topic.
