<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Data | US Museums and Libraries Analysis</title>
  <meta name="description" content="Chapter 3 Data | US Museums and Libraries Analysis" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Data | US Museums and Libraries Analysis" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data | US Museums and Libraries Analysis" />
  
  
  

<meta name="author" content="Group 5: Yuanyi Hu, Yining Ma, Yi Zhuang" />


<meta name="date" content="2022-12-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="proposal.html"/>
<link rel="next" href="results.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">USMuseums&Libraries</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="proposal.html"><a href="proposal.html"><i class="fa fa-check"></i><b>2</b> Proposal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="proposal.html"><a href="proposal.html#research-topic"><i class="fa fa-check"></i><b>2.1</b> Research topic</a></li>
<li class="chapter" data-level="2.2" data-path="proposal.html"><a href="proposal.html#data-availability"><i class="fa fa-check"></i><b>2.2</b> Data availability</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>3</b> Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data.html"><a href="data.html#sources"><i class="fa fa-check"></i><b>3.1</b> Sources</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data.html"><a href="data.html#museum-data-source"><i class="fa fa-check"></i><b>3.1.1</b> Museum Data Source</a></li>
<li class="chapter" data-level="3.1.2" data-path="data.html"><a href="data.html#library-data-source"><i class="fa fa-check"></i><b>3.1.2</b> Library Data Source</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data.html"><a href="data.html#cleaning-transformation"><i class="fa fa-check"></i><b>3.2</b> Cleaning / transformation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data.html"><a href="data.html#museum-data-cleaning"><i class="fa fa-check"></i><b>3.2.1</b> Museum Data Cleaning</a></li>
<li class="chapter" data-level="3.2.2" data-path="data.html"><a href="data.html#library-data-cleaning"><i class="fa fa-check"></i><b>3.2.2</b> Library Data Cleaning</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data.html"><a href="data.html#missing-value-analysis"><i class="fa fa-check"></i><b>3.3</b> Missing value analysis</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data.html"><a href="data.html#museum-data"><i class="fa fa-check"></i><b>3.3.1</b> Museum Data</a></li>
<li class="chapter" data-level="3.3.2" data-path="data.html"><a href="data.html#library-data"><i class="fa fa-check"></i><b>3.3.2</b> Library Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>4</b> Results</a>
<ul>
<li class="chapter" data-level="4.1" data-path="results.html"><a href="results.html#museum-in-us"><i class="fa fa-check"></i><b>4.1</b> Museum in US</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="results.html"><a href="results.html#discipline-museums-distribution-in-states"><i class="fa fa-check"></i><b>4.1.1</b> Discipline Museums Distribution in States</a></li>
<li class="chapter" data-level="4.1.2" data-path="results.html"><a href="results.html#relationship-between-income-and-discipline"><i class="fa fa-check"></i><b>4.1.2</b> Relationship Between Income and Discipline</a></li>
<li class="chapter" data-level="4.1.3" data-path="results.html"><a href="results.html#relationship-between-location-and-revenue"><i class="fa fa-check"></i><b>4.1.3</b> Relationship Between Location and Revenue</a></li>
<li class="chapter" data-level="4.1.4" data-path="results.html"><a href="results.html#new-museums-trend"><i class="fa fa-check"></i><b>4.1.4</b> New Museums Trend</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="results.html"><a href="results.html#library-in-us"><i class="fa fa-check"></i><b>4.2</b> Library in US</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="results.html"><a href="results.html#analysis-of-library-2020"><i class="fa fa-check"></i><b>4.2.1</b> Analysis of Library 2020</a></li>
<li class="chapter" data-level="4.2.2" data-path="results.html"><a href="results.html#time-series-analysis"><i class="fa fa-check"></i><b>4.2.2</b> Time Series Analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="results.html"><a href="results.html#museum-and-library-in-us"><i class="fa fa-check"></i><b>4.3</b> Museum and Library in US</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="results.html"><a href="results.html#museum-map"><i class="fa fa-check"></i><b>4.3.1</b> Museum map</a></li>
<li class="chapter" data-level="4.3.2" data-path="results.html"><a href="results.html#library-map"><i class="fa fa-check"></i><b>4.3.2</b> Library map</a></li>
<li class="chapter" data-level="4.3.3" data-path="results.html"><a href="results.html#relationship-between-museum-and-library-distributions"><i class="fa fa-check"></i><b>4.3.3</b> Relationship between museum and library distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>5</b> Interactive component</a></li>
<li class="chapter" data-level="6" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>6</b> Conclusion</a>
<ul>
<li class="chapter" data-level="6.1" data-path="interactive-component.html"><a href="interactive-component.html#museum"><i class="fa fa-check"></i><b>6.1</b> Museum</a></li>
<li class="chapter" data-level="6.2" data-path="interactive-component.html"><a href="interactive-component.html#library"><i class="fa fa-check"></i><b>6.2</b> Library</a></li>
<li class="chapter" data-level="6.3" data-path="conclusion.html"><a href="conclusion.html#regional-cultural-development"><i class="fa fa-check"></i><b>6.3</b> Regional Cultural development</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">US Museums and Libraries Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Data<a href="data.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="sources" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Sources<a href="data.html#sources" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="museum-data-source" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Museum Data Source<a href="data.html#museum-data-source" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Museum data is from the official website of the Institute of Museum and Library Services(IMLS), and we use the latest version that collected in 2018. There are three csv files that contain different type of museums. The second file just contains GMU museums, the third file just contains HSC museums.</p>
<p>The three files contain 7431, 7961, 14786 museums, and each file has 58 variables, including some basic information, like the id, location, contact, ruledate information, and the income and revenue information.</p>
<p>And we choose to mainly analyse the state, discipline, income and the established dates, therefore, we select the relevant columns to conduct our analysis. The discipline contains 9 values, reflecting 9 kinds of museums; we choose IncomeCD15 to present museum income, which 9 ranges of income from 0 to 50,000,000 and greater; rule_date the registered nonprofit organization was recognized as having obtained their formal tax-exempt status by the IRS, we use this column to present the established date.</p>
</div>
<div id="library-data-source" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Library Data Source<a href="data.html#library-data-source" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The library data set is also from <a href="https://www.imls.gov/" class="uri">https://www.imls.gov/</a> which is the website of the Institute of Museum and Library Service. This institute provide several data set regarding museum and library across the nation. We use the data set of The Public Libraries Survey (PLS) which supplied annually by public libraries across the country on when, where, and how library services are changing to meet the needs of the public.</p>
<p>The data was collected by the institute. The survey is administered by Data Coordinators and the requested data was collected from local public libraries. There is a web-based reporting system State Data Coordinators used report data to the institute.</p>
<p>The survey was conducted annually since 1988 and the website provides data files since 1992. During past years, the content on the survey changed 3 times and the format of the data sets are slightly differences.</p>
<p>As for the data file, the data files are available on the web site and is a public-used data set which means some of the data was removed aimed to protect the confidentiality of individually identifiable survey respondents. Our project use this public-used data set which was encoded and pre-processed and provides a documentation file to help the user correctly understand the data set and gives detailed information about the data set.</p>
<p>The data set provides statistics on the status of public libraries in the United States collected from approximately 9,000 public libraries with approximately 17,000 individual public library outlets in the 50 states, the District of Columbia, and outlying territories. The data set contains information about library visits, circulation, size of collections, public service hours, staffing, electronic resources, operating revenues and expenditures and number of service outlets. We basically use the state wide data which contains 55 rows and more than 100 variables.</p>
</div>
</div>
<div id="cleaning-transformation" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Cleaning / transformation<a href="data.html#cleaning-transformation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="museum-data-cleaning" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Museum Data Cleaning<a href="data.html#museum-data-cleaning" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We firstly select the columns that we need from three files and then modify the data type of ID from string to numeric to match each other and then merge them together.</p>
<p>Then we created different data frames group by state, discipline, income, and decades of the rule date to further show the distribution of museums in different disciplines and states, the relationships between variables, and the museum growth trends from 1900s to 2010s.</p>
</div>
<div id="library-data-cleaning" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Library Data Cleaning<a href="data.html#library-data-cleaning" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data format in the library data set is quite clean and suitable for us to use. Thus, we didn’t do much on cleaning them but only went through the variables in the data set and select the variables that we are interested in. The state data in the data set is coded. As a result, we used another data set which contains the name of state and the code of state and combine them to get the state name we need.</p>
</div>
</div>
<div id="missing-value-analysis" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Missing value analysis<a href="data.html#missing-value-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="museum-data" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Museum Data<a href="data.html#museum-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>##        MID DISCIPLINE    ADSTATE INCOMECD15 RULEDATE15 
##          3          0          0       8677       8682</code></pre>
<p><img src="finalproj_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>There is no missing data in discipline and state, but are 8677(28.8%) empty value in incomecd, and 8682(28.8%) empty value in rule date.
Most missing cases are missing rule date and incomecd together, which means missing these two variables are correlated.
If MID is missing, we think it is not a valid museum record, and will delete this record.</p>
<p>We can see that after removing missing data, the rest of data is still representative since we can restore the shape of the map of the USA by plotting the rest of the data according to each pair of the location variable. This means that data collection covers each state and the amount of missing data is reasonable because the rest of data keeps the key geographic and discipline information. Hence, it’s valid to explore the distribution of disciplines and locations in the following sections by using the rest of data.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="library-data" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Library Data<a href="data.html#library-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We first visualize the missing data in our data set and discuss the pattern it has. This is an important step for us to under stand our data.</p>
<div id="library-data-set" class="section level4 hasAnchor" number="3.3.2.1">
<h4><span class="header-section-number">3.3.2.1</span> Library Data Set<a href="data.html#library-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Library data of 2020
In this project, we first analyze the data of Library in US in 2020. According to the document of the data set, all the missing data is filled with ‘-1’. Thus, we will visualize the distribution of ‘-1’ in this data set.</li>
</ol>
<p><img src="finalproj_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>As we can see from the graph, the only row has missing data is the state with code ‘VI’ which is Virgin Islands. All other data is completed. As this state is an outlying area of the United States and missing data are primarily some statistic data about the revenue and resource data of the library, we believe it is reasonable to keep the data as ‘-1’ in these rows which have little effect on our visualization.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>This graph shows the pattern further which is most rows (data of different state) is complete and provide us a relatively good data quality to analyze and visualize the libraries in US.</p>
</div>
<div id="time-series-missing-data-analysis" class="section level4 hasAnchor" number="3.3.2.2">
<h4><span class="header-section-number">3.3.2.2</span> Time series missing data analysis<a href="data.html#time-series-missing-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Moreover, to discuss the changing pattern of libraries in US, we collect library data in different years. Although we can easily read in all the raw data, band them together and select the variables we are interested in, we believe that to store such a large set of data makes the requirement of space of this project too big and the transforming progress takes a lot of time. As a result, we choose the variable in each years’ data and store them in a csv file. As the data update once a year, it will not take too much time to add new data to this file. As for the data format, we keep it same with the original data and all the missing data is filled with ‘-1’.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>As we can see from the graph, there are three states having missing data through the years which are GU(Guam), MP(Northern Mariana Islands) and VI(Virgin Islands). All of these states are outlying area of the United States. Thus, we keep these data with its original form.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>As we can see in this chart, among all the rows having missing data, some of them missing quite a lot of data while others only miss one or two data. As we result, we would like to further see the missing data. We select all the rows of the three states and data is as below:</p>
<pre><code>##    STABR YEAR POPU_LSA CENTLIB BRANLIB BKMOB  BKVOL EBOOK VISITS
## 1     GU 2020   168678       1       5     0 286930     0  35115
## 2     MP 2020    53883       1       2     1  83624  5500  44710
## 3     VI 2020   106405       0       5     3 176762    -1     -1
## 4     GU 2019   168678       1       5     0 278963     0 100095
## 5     MP 2019    51433       1       2     1  82199  5000 147983
## 6     VI 2019   106405       0       5     3 176762    -1     -1
## 7     GU 2018   167358       1       5     0 276631     0  75119
## 8     MP 2018    51994       1       2     1  92000  5000 126778
## 9     VI 2018   106405       0       4     3     -1    -1     -1
## 10    GU 2017   164229       1       5     0 272720   200  81572
## 11    MP 2017    53883       1       2     0  92141  5000 104224
## 12    GU 2016   159358       1       5     0 269270   200  71813
## 13    GU 2015   159358       1       5     0 266695   200  72223
## 14    GU 2014   159358       1       5     0 263486  1335 103593
## 15    MP 2014    53883       1       1     0     -1    -1     -1
## 16    VI 2014   106405       0       5     1     -1    -1     -1
## 17    GU 2013   159358       1       5     1 260586     0  98969
## 18    MP 2013    53883       1       1     0     -1    -1     -1
## 19    VI 2013   106405       0       5     1     -1    -1     -1
## 20    GU 2012   159358       1       5     1 258241  1278  75472
## 21    MP 2012    53883       1       1     0     -1    -1     -1
## 22    VI 2012   106405       0       5     1     -1    -1     -1
## 23    GU 2011   159358       1       5     1 255277     0  80016
## 24    MP 2011    53883       1       1     0     -1    -1     -1
## 25    VI 2011   106405       0       5     1     -1    -1     -1
## 26    GU 2010   180692       1       5     1 204503     0  84019
## 27    MP 2010    53883       1       1     0     -1    -1     -1
## 28    VI 2010   106405       0       5     1     -1    -1     -1
## 29    GU 2009   175459       1       5     1 210079     0  60763
## 30    MP 2009       -1      -1      -1    -1     -1    -1     -1
## 31    VI 2009       -1      -1      -1    -1     -1    -1     -1
## 32    GU 2008    25984       1       5     1 211772    -1  70061
## 33    MP 2008       -1      -1      -1    -1     -1    -1     -1
## 34    VI 2008       -1      -1      -1    -1     -1    -1     -1
## 35    GU 2007       -1      -1      -1    -1     -1    -1     -1
## 36    MP 2007       -1      -1      -1    -1     -1    -1     -1
## 37    VI 2007       -1      -1      -1    -1     -1    -1     -1
## 38    GU 2006       -1      -1      -1    -1     -1    -1     -1
## 39    MP 2006       -1      -1      -1    -1     -1    -1     -1
## 40    VI 2006       -1      -1      -1    -1     -1    -1     -1</code></pre>
<p>From the table, we can see that in some year(2016,2015), two of the states didn’t report the data and among all the reported data, most of the missing data is in early years. As we would like to see the trend of the data, we also keep the original data in this data set in stead of filling them in some way.</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="proposal.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yiningma1001/USMuseumsAndLibraries/edit/main/data.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/yiningma1001/USMuseumsAndLibraries/blob/main/data.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
